version: '3.2'
services:
  web:
    build: .
    command: npm run server
    volumes:
      - .:/usr/app/
    ports:
      - '8000:8000'
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - type: bind
        source: ./api/dist
        target: /swagger
