version: '3.2'
services:
  web:
    image: sam/katam-user-microservice-ts
    build: .
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: docker
    volumes:
      - .:/usr/src/app
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - type: bind
        source: ./api/dist
        target: /swagger
